name: "Vault Secrets"
description: "Action to load secrets from Vault and set them as environment variables for subsequent steps."

runs:
  using: "composite"
  steps:
    - name: Install Vault
      uses: eLco/setup-vault@v1
      with:
        vault_version: ${{ env.VAULT_VERSION }}

    - name: Build VAULT HELPER URL
      shell: bash
      run: |
        echo "VAULT_HELPER_URL=https://raw.githubusercontent.com/proxmox-home-lab/.github/${VAULT_HELPER_VERSION}/vault-helper.sh" >> "$GITHUB_ENV"

    - name: Load secrets from Vault
      shell: bash
      run: |
        source <(curl -s "$VAULT_HELPER_URL")
        env
