name: "Vault Secrets"
description: "Action to load secrets from Vault and set them as environment variables for subsequent steps."

inputs:
  vault_helper_version:
    description: "The version of the vault-helper script to use"
    required: true
    default: "main"
  vault_version:
    description: "The version of Vault to install"
    required: true
    default: "v1.20.2"
  vault_agent_hcl_file:
    description: "Optional path to a Vault Agent HCL configuration file to use for authentication and secret retrieval"
    required: true
    default: vault-agent.hcl

runs:
  using: "composite"
  steps:
    - name: Install Vault
      uses: eLco/setup-vault@v1
      with:
        vault_version: ${{ inputs.vault_version }}

    - name: Build VAULT HELPER URL
      shell: bash
      run: |
        echo "VAULT_HELPER_URL=https://raw.githubusercontent.com/proxmox-home-lab/.github/${{ inputs.vault_helper_version }}/vault-helper.sh" >> "$GITHUB_ENV"

    - name: Load secrets from Vault
      shell: bash
      run: |
        source <(curl -s "$VAULT_HELPER_URL")
        env
