name: "Terragrunt Plan/Apply Summarize"
description: "Extract only STDOUT/WARN/ERROR terraform/tofu lines and emit summary."

inputs:
  log_path:
    required: true
  max_chars:
    required: false
    default: "60000"

outputs:
  summary:
    value: ${{ steps.export.outputs.summary }}

runs:
  using: "composite"
  steps:
    - name: Run summarize script
      id: export
      shell: bash
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/summarize.py" \
          "${{ inputs.log_path }}" \
          "${{ inputs.max_chars }}" >> "$GITHUB_OUTPUT"